---
version: "2.1"
services:
  frontend-angular:
    image: frontend-angular
    container_name: frontend-angular
    build:
      context: ./angular
      dockerfile: Dockerfile
    ports:
      - 4200:4200
      - 80:80
    environment:
      - PGUID=1000
      - PGID=1000
    restart: unless-stopped
    
  
  backend-python:
    image: backend-python
    container_name: backend-python
    build:
      context: ./backend-Python
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: unless-stopped

  mongo:
    image: mongo:latest
    restart: always
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: backend
    volumes: 
      - "mongo_db:/data/db"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

volumes:
  mongo_db: